version: '3.8'

services:
  deploy-test-123:
    container_name: cavity-test-deploy-123
    image: ${DOCKER_IMAGE}
    ports:
      - "3000:3000"
    networks:
      - server_backend

networks:
  server_backend:
    name: server_backend
