version: '3.8'

services:
  node-app:
    container_name: node-app
    image: ${DOCKER_IMAGE}
    environment:
      NODE_ENV: 'production'
      PORT: 3000
      TZ: 'UTC'
    ports:
      - "3052:3052"
    networks:
      - server_backend

networks:
  server_backend:
    name: server_backend
