name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

env:
    REGISTRY: 828446050677.dkr.ecr.ap-south-1.amazonaws.com/deploy-test
    IMAGE_TAG: ${{ github.sha }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: test-deploy  # Set the environment to test-deploy

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3  # Use v3 for both jobs
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build, tag, and push Docker image to Amazon ECR
      - name: Build, tag, and push Docker image to Amazon ECR
        run: |
          echo "Building Docker image..."
          docker build -t $REGISTRY:$IMAGE_TAG .
          echo "Pushing Docker image to ECR..."
          docker push $REGISTRY:$IMAGE_TAG


  deploy_to_ec2:
    runs-on: ['self-hosted', 'deploytest123']
    needs: build-and-push

    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Trigger EC2 to pull latest Docker image
        run: | 
          # sudo cp /home/ubuntu/test-docker/docker-compose.yml .
          export DOCKER_IMAGE=$REGISTRY:$IMAGE_TAG
          cd "${GITHUB_WORKSPACE}"
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 828446050677.dkr.ecr.ap-south-1.amazonaws.com
          docker-compose -f docker-compose-123.yml up -d